version: "3.7"
services:
  application:
    image: ${IMAGE_DEV}
    container_name: ${APP_NAME}-dev
    restart: on-failure
    working_dir: /src/${APP_NAME}
    environment:
      - APP_ENV=development
    volumes:
      - ../:/src/${APP_NAME}
      - ~/.ssh:/home/developer/.ssh
    command: ['tail', '-f', '/dev/null']
    networks:
      application:

networks:
  application:
    name: ${APP_NAME}-network
